=== gouderhicham/Thesis/xml/uni.dtd
<!ELEMENT Students (Student+)>
<!ELEMENT Student (FirstName, FamilyName, Age, Level, Speciality, Average, Address?)>
<!ATTLIST Student RegistrationNumber CDATA #REQUIRED>

<!ELEMENT FirstName (#PCDATA)>
<!ELEMENT FamilyName (#PCDATA)>
<!ELEMENT Age (#PCDATA)>
<!ELEMENT Level (#PCDATA)>
<!ELEMENT Speciality (#PCDATA)>
<!ELEMENT Average (#PCDATA)>

<!ELEMENT Address (Number, City, PostalCode)>
<!ELEMENT Number (#PCDATA)>
<!ELEMENT City (#PCDATA)>
<!ELEMENT PostalCode (#PCDATA)>

=== gouderhicham/Thesis/xml/uni.xml
<!DOCTYPE Students SYSTEM "uni.dtd">
<Students>
    <Student RegistrationNumber="12345">
        <FirstName>Gouder</FirstName>
        <FamilyName>Hicham</FamilyName>
        <Age>21</Age>
        <Level>3</Level>
        <Speciality>Computer Science</Speciality>
        <Average>85.5</Average>
        <Address>
            <Number>123</Number>
            <City>El oued</City>
            <PostalCode>39000</PostalCode>
        </Address>
    </Student>
</Students>
